from typing import List, Optional, Union
from pydantic import BaseModel, Field, ConfigDict


class GradeBreakdownItem(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    criterion: str = Field(..., description="Marking criterion or point description")
    marks_awarded: Union[float, int] = Field(..., description="Marks given")
    max_possible: Union[float, int] = Field(..., description="Maximum marks for this item")
    reason: str = Field(..., description="Explanation for awarded marks")
    # Keep the historical string field for compatibility, but also preserve the
    # original list of evidence snippets for reliable PDF anchoring.
    evidence: Optional[str] = Field(None, description="Relevant student text snippet(s), possibly joined")
    evidence_list: Optional[List[str]] = Field(
        default=None,
        description="Optional list of 1-3 verbatim evidence snippets from the student answer"
    )
    comments_summary: Optional[str] = Field(None, description="Grader comment for this specific item (if any)")

    # Holistic grading fields (only populated when holistic_grading=True on the parent doc)
    sub_question: Optional[str] = Field(None, alias="_sub_question", description="Sub-question identifier (holistic grading)")
    student_label: Optional[str] = Field(None, alias="_student_label", description="Student's label for this sub-question (holistic grading)")
    correct_points_with_marks: Optional[List[dict]] = Field(None, alias="_correct_points_with_marks", description="Per-point marks for holistic annotation [{text, marks}]")


class StudentGradeDocument(BaseModel):
    student_id: str = Field(..., description="Student name or ID")
    question_number: str = Field(..., description="Question number (e.g. '1', '4.2')")
    total_marks_awarded: Union[float, int] = Field(..., description="Total marks awarded")
    total_max_possible: Union[float, int] = Field(..., description="Total possible marks")
    overall_reason: str = Field(..., description="Summary reason for total score")

    breakdown: List[GradeBreakdownItem] = Field(
        ..., description="Detailed per-criterion breakdown"
    )

    comments: List[str] = Field(
        default_factory=list,
        description="Structured list of LLM-generated feedback comments for the whole question"
    )

    # Notes that are useful for debugging or reporting but are not suitable for PDF anchoring.
    guardrail_warnings: List[str] = Field(
        default_factory=list,
        description="Warnings generated by post-processing guardrails (not intended for PDF annotation)"
    )
    unanchored_comments: List[str] = Field(
        default_factory=list,
        description="LLM comments that did not meet the strict annotation-friendly format"
    )

    # Holistic grading flag
    holistic_grading: Optional[bool] = Field(None, description="True when holistic grading mode was used (no marking criteria)")

    # References & Metadata
    extracted_at: str = Field(..., description="ISO timestamp of grading")
    question_id: Optional[str] = Field(None, description="pac_questions _id")
    model_answer_id: Optional[str] = Field(None, description="model_answers _id")
    student_answer_id: Optional[str] = Field(None, description="student_assignments _id")
